/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato3d;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileWriter;
import java.io.*;
/**
 *
 * @author oriente
 */
public class Gatito extends javax.swing.JFrame {
    int cont=0;
    int pos[]=new int[30];
    int jugadas_ganadoras[]=new int[30];
    int jugador1[]=new int[30];
    int jugador2[]=new int[30];
    int ind1=0;
    int ind2=0;
    //declaraciones
    File archivo=new File("JugadasGanadas.txt");
    String saludo=" "; //le puse saludo porque fue el de prueba xD 
    /**
     * Creates new form Gatito
     */
    public Gatito() {
        initComponents();
        for(int i=0;i<30;i++)
            pos[i]=0;
    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gatito().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        getContentPane().add(A1);
        A1.setBounds(2, 12, 41, 34);

        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        getContentPane().add(A4);
        A4.setBounds(2, 52, 41, 34);

        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A9ActionPerformed(evt);
            }
        });
        getContentPane().add(A9);
        A9.setBounds(104, 92, 41, 34);

        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        getContentPane().add(A2);
        A2.setBounds(53, 12, 41, 34);

        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        getContentPane().add(A5);
        A5.setBounds(53, 52, 41, 34);

        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        getContentPane().add(A7);
        A7.setBounds(2, 92, 41, 34);

        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        getContentPane().add(A6);
        A6.setBounds(104, 52, 41, 34);

        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8ActionPerformed(evt);
            }
        });
        getContentPane().add(A8);
        A8.setBounds(53, 92, 41, 34);

        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        getContentPane().add(A3);
        A3.setBounds(104, 12, 41, 34);

        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(189, 141, 41, 34);

        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        getContentPane().add(B4);
        B4.setBounds(189, 182, 41, 34);

        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        getContentPane().add(B7);
        B7.setBounds(189, 222, 41, 31);

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(236, 182, 40, 34);

        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        getContentPane().add(B8);
        B8.setBounds(236, 222, 40, 31);

        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        getContentPane().add(B3);
        B3.setBounds(282, 141, 41, 34);

        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        getContentPane().add(B6);
        B6.setBounds(282, 182, 38, 34);

        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        getContentPane().add(B9);
        B9.setBounds(282, 222, 38, 31);

        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(236, 141, 40, 35);

        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        getContentPane().add(C2);
        C2.setBounds(424, 264, 41, 35);

        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        getContentPane().add(C7);
        C7.setBounds(377, 346, 41, 35);

        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1);
        C1.setBounds(377, 264, 41, 35);

        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8ActionPerformed(evt);
            }
        });
        getContentPane().add(C8);
        C8.setBounds(423, 346, 43, 35);

        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        getContentPane().add(C5);
        C5.setBounds(424, 305, 41, 35);

        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        getContentPane().add(C4);
        C4.setBounds(377, 305, 41, 35);

        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        getContentPane().add(C6);
        C6.setBounds(472, 305, 41, 35);

        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        getContentPane().add(C3);
        C3.setBounds(472, 264, 41, 35);

        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });
        getContentPane().add(C9);
        C9.setBounds(472, 346, 41, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gato-siberiano-0304201402.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 670, 420);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 220, 97, 29);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 220, 97, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //declaraciones

 //funcion, esta funcion se manda a llamar en guardar ganador 
    private void GuardarTxt(){
        try{
            //vemos la jugada que gano
            try ( //Crear objeto FileWriter que sera el que nos ayude a escribir sobre archivo
                    FileWriter escribir = new FileWriter(archivo,true)) {
                //vemos la jugada que gano
                for(int i=0;i<27;i++){
                    saludo= Integer.toString(jugadas_ganadoras[i]); //lo convierto de entero a string
                    escribir.write(saludo);
                    escribir.write(" ");
                }   //Escribimos en el archivo con el metodo write
                escribir.write("\n");
                //Cerramos la conexion
            }
        }
        //Si existe un problema al escribir cae aqui
        catch(Exception e){
            System.out.println("Error al escribir");
        }
        LeeFichero();
    }
     
    private void LeeFichero() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {
             // Apertura del fichero y creacion de BufferedReader para poder
            // hacer una lectura comoda (disponer del metodo readLine()).
            archivo = new File ("JugadasGanadas.txt");
            fr = new FileReader (archivo);
             br = new BufferedReader(fr);
         System.out.println("Leyendo desde archivo");
         // Lectura del fichero
         String linea;
         while((linea=br.readLine())!=null)      // imprime lo que haya en el archivo
            System.out.println(linea);
      }
      catch(Exception e){
         e.printStackTrace();
      }finally{
         // En el finally cerramos el fichero, para asegurarnos
         // que se cierra tanto si todo va bien como si salta 
         // una excepcion.
         try{                    
            if( null != fr ){   
               fr.close();     
            }                  
         }catch (Exception e2){ 
            e2.printStackTrace();
         }
      }
}
    
    
     
    private void guardar_ganador(){
        int tam=0;
        if(pos[0]==1){ 
            tam=ind1;
            for(int i=0;i<27;i++){
                if(i<tam)
                    jugadas_ganadoras[i]=jugador1[i];
                else
                    jugadas_ganadoras[i]=0;
            }
        }
        else {
            tam=ind2;
            for(int i=0;i<27;i++){
                if(i<tam)
                    jugadas_ganadoras[i]=jugador2[i];
                else
                    jugadas_ganadoras[i]=0;
            }
        }
        GuardarTxt();
        for(int i=0;i<27;i++)
            System.out.print(" "+jugadas_ganadoras[i]);
     
    }
    
    private void checar_ganador(){
        int f=0;
        if(pos[1]==pos[4] && pos[4]==pos[7] && pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[2]==pos[5] && pos[5]==pos[8] && pos[2]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[3]==pos[6] && pos[6]==pos[9] && pos[3]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[1]==pos[2] && pos[2]==pos[3] && pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[4]==pos[5] && pos[5]==pos[6]&& pos[4]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[7]==pos[8] && pos[8]==pos[9] && pos[7]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[1]==pos[5] && pos[5]==pos[9] && pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[3]==pos[5] && pos[5]==pos[7] && pos[3]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[10]==pos[13] && pos[13]==pos[16]&& pos[10]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[12]==pos[15] && pos[15]==pos[18]&& pos[12]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[10]==pos[11] && pos[11]==pos[12] && pos[10]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[16]==pos[17] && pos[17]==pos[18] && pos[16]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[19]==pos[20] && pos[20]==pos[21] && pos[19]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[22]==pos[23] && pos[23]==pos[24] && pos[22]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[25]==pos[26] && pos[26]==pos[27] && pos[25]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[19]==pos[22] && pos[22]==pos[25] && pos[19]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[20]==pos[23] && pos[23]==pos[26] && pos[20]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[21]==pos[24] && pos[24]==pos[27] && pos[21]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[19]==pos[23] && pos[23]==pos[27] && pos[19]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[21]==pos[23] && pos[23]==pos[25]&& pos[21]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[1]==pos[13] && pos[13]==pos[25]&& pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[1]==pos[11] && pos[11]==pos[21]&& pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[7]==pos[17] && pos[17]==pos[27]&& pos[7]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        else if(pos[3]==pos[15] && pos[15]==pos[27]&& pos[3]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }
        if(f==1){
            guardar_ganador();
        }
        
            
    }
    
    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // Posicion 1
        if(cont==0){
            A1.setText("X");
            cont++;
            pos[1]=1;
            jugador1[ind1++]=1;
        }
        else{
            A1.setText("O");
            cont--;
            pos[1]=2;
            jugador2[ind2++]=1;
        }
        checar_ganador();
        A1.setEnabled(false);
    }//GEN-LAST:event_A1ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        //Posicion2
        if(cont==0){
            A4.setText("X");
            cont++;
            pos[4]=1;
            jugador1[ind1++]=4;
        }
         else{
            A4.setText("O");
            cont--;
            pos[4]=2;
            jugador2[ind2++]=4;
        }
        checar_ganador();
        A4.setEnabled(false);
    }//GEN-LAST:event_A4ActionPerformed

    private void A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A9ActionPerformed
        //Posicion3
        if(cont==0){
            A9.setText("X");
            cont++;
            pos[9]=1;
            jugador1[ind1++]=9;
        }
         else{
            A9.setText("O");
            cont--;
            pos[9]=2;
            jugador2[ind2++]=9;
        }
        checar_ganador();
        A9.setEnabled(false);
    }//GEN-LAST:event_A9ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // Posicion4
         if(cont==0){
            A2.setText("X");
            cont++;
            pos[2]=1;
            jugador1[ind1++]=2;
        }
         else{
            A2.setText("O");
            cont--;
            pos[2]=2;
            jugador2[ind2++]=2;
        }
         
        checar_ganador();
        A2.setEnabled(false);
    }//GEN-LAST:event_A2ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed

        // Posicion5
         if(cont==0){
            A6.setText("X");
            cont++;
            pos[6]=1;
            jugador1[ind1++]=6;
        }
         else{
            A6.setText("O");
            cont--;
            pos[6]=2;
            jugador2[ind2++]=6;
        }
         
        checar_ganador();
         A6.setEnabled(false);
    }//GEN-LAST:event_A6ActionPerformed

    private void A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8ActionPerformed
           // Posicion6
         if(cont==0){
            A8.setText("X");
            cont++;
            pos[8]=1;
            jugador1[ind1++]=8;
        }
         else{
            A8.setText("O");
            cont--;
            pos[8]=2;
            jugador2[ind2++]=8;
        }
         
           checar_ganador();
         A8.setEnabled(false);
    }//GEN-LAST:event_A8ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // Posicion7
         if(cont==0){
            A3.setText("X");
            cont++;
            pos[3]=1;
            jugador1[ind1++]=3;
        }
         else{
            A3.setText("O");
            cont--;
            pos[3]=2;
            jugador2[ind2++]=3;
        }
         
        checar_ganador();
        A3.setEnabled(false);
    }//GEN-LAST:event_A3ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
         // Posicion8
         
         if(cont==0){
            A5.setText("X");
            cont++;
            pos[5]=1;
            jugador1[ind1++]=5;
        }
         else{
            A5.setText("O");
            cont--;
            pos[5]=2;
            jugador2[ind2++]=5;
        }
         checar_ganador();
        A5.setEnabled(false);
    }//GEN-LAST:event_A5ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
       
        // Posicion9
         if(cont==0){
            A7.setText("X");
            cont++;
            pos[7]=1;
            jugador1[ind1++]=7;
        }
         else{
            A7.setText("O");
            cont--;
            pos[7]=2;
            jugador2[ind2++]=7;
        }
         checar_ganador();
        A7.setEnabled(false);
    }//GEN-LAST:event_A7ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        //Posicion2.1
        
       if(cont==0){
            B1.setText("X");
            cont++;
            pos[10]=1;
            jugador1[ind1++]=10;
        }
         else{
            B1.setText("O");
            cont--;
            pos[10]=2;
            jugador2[ind2++]=10;
        }
       checar_ganador();
        B1.setEnabled(false);
    }//GEN-LAST:event_B1ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
         //Posicion2.2
       
       if(cont==0){
            B4.setText("X");
            cont++;
            pos[13]=1;
            jugador1[ind1++]=13;
        }
         else{
            B4.setText("O");
            cont--;
            pos[13]=2;
            jugador2[ind2++]=13;
        }
         checar_ganador();
       B4.setEnabled(false);
    }//GEN-LAST:event_B4ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
           //Posicion2.3
         
       if(cont==0){
            B7.setText("X");
            cont++;
            pos[16]=1;
            jugador1[ind1++]=16;
        }
         else{
            B7.setText("O");
            cont--;
            pos[16]=2;
            jugador2[ind2++]=16;
        }
         checar_ganador();
       B7.setEnabled(false);
    }//GEN-LAST:event_B7ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
             //Posicion2.4
          
       if(cont==0){
            B2.setText("X");
            cont++;
            pos[11]=1;
            jugador1[ind1++]=11;
        }
         else{
            B2.setText("O");
            cont--;
            pos[11]=2;
            jugador2[ind2++]=11;
        }
          checar_ganador();
       B2.setEnabled(false);
    }//GEN-LAST:event_B2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
              //Posicion2.5
              jButton14.setBackground(java.awt.Color.red);
       /*if(cont==0){
            jButton14.setText("X");
            cont++;
        }
         else{
            jButton14.setText("O");
            cont--;
        }*/
    }//GEN-LAST:event_jButton14ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
              //Posicion2.6
              
       if(cont==0){
            B8.setText("X");
            cont++;
            pos[17]=1;
            jugador1[ind1++]=17;
        }
         else{
            B8.setText("O");
            cont--;
            pos[17]=2;
            jugador2[ind2++]=17;
        }
       checar_ganador();
       B8.setEnabled(false);
    }//GEN-LAST:event_B8ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
               //Posicion2.7
              
       if(cont==0){
            B3.setText("X");
            cont++;
            pos[12]=1;
            jugador1[ind1++]=12;
        }
         else{
            B3.setText("O");
            cont--;
            pos[12]=2;
            jugador2[ind2++]=12;
        }
        checar_ganador();
       B3.setEnabled(false);
    }//GEN-LAST:event_B3ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
                //Posicion2.8
                
       if(cont==0){
            B6.setText("X");
            cont++;
            pos[15]=1;
            jugador1[ind1++]=15;
        }
         else{
            B6.setText("O");
            cont--;
            pos[15]=2;
            jugador2[ind2++]=15;
        }
       checar_ganador();
       B6.setEnabled(false);
    }//GEN-LAST:event_B6ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
              //Posicion2.9
              
       if(cont==0){
            B9.setText("X");
            cont++;
            pos[18]=1;
            jugador1[ind1++]=18;
        }
         else{
            B9.setText("O");
            cont--;
            pos[18]=2;
            jugador2[ind2++]=18;
        }
       checar_ganador();
       B9.setEnabled(false);
    }//GEN-LAST:event_B9ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
               //Posicion3.1
               
       if(cont==0){
            C1.setText("X");
            cont++;
            pos[19]=1;
            jugador1[ind1++]=19;
        }
         else{
            C1.setText("O");
            cont--;
            pos[19]=2;
            jugador2[ind2++]=19;
        }
       checar_ganador();
       C1.setEnabled(false);
    }//GEN-LAST:event_C1ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
                 //Posicion3.2
                 
       if(cont==0){
            C4.setText("X");
            cont++;
            pos[22]=1;
            jugador1[ind1++]=22;
        }
         else{
            C4.setText("O");
            cont--;
            pos[22]=2;
            jugador2[ind2++]=22;
        }
       checar_ganador();
       C4.setEnabled(false);
    }//GEN-LAST:event_C4ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
                    //Posicion3.3
                   
       if(cont==0){
            C7.setText("X");
            cont++;
            pos[25]=1;
            jugador1[ind1++]=25;
        }
         else{
            C7.setText("O");
            cont--;
            pos[25]=2;
            jugador2[ind2++]=25;
        }
        checar_ganador();
       C7.setEnabled(false);
    }//GEN-LAST:event_C7ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        //Posicion3.4
        
       if(cont==0){
            C2.setText("X");
            cont++;
            pos[20]=1;
            jugador1[ind1++]=20;
        }
         else{
            C2.setText("O");
            cont--;
            pos[20]=2;
            jugador2[ind2++]=20;
        }
       checar_ganador();
       C2.setEnabled(false);
    }//GEN-LAST:event_C2ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        //Posicion3.5
        
       if(cont==0){
            C5.setText("X");
            cont++;
            pos[23]=1;
            jugador1[ind1++]=23;
        }
         else{
            C5.setText("O");
            cont--;
            pos[23]=2;
            jugador2[ind2++]=23;
        }
       checar_ganador();
       C5.setEnabled(false);
    }//GEN-LAST:event_C5ActionPerformed

    private void C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8ActionPerformed
        // TODO add your handling code here:
        //Posicion3.6
        
       if(cont==0){
            C8.setText("X");
            cont++;
            pos[26]=1;
            jugador1[ind1++]=26;
        }
         else{
            C8.setText("O");
            cont--;
            pos[26]=2;
            jugador2[ind2++]=26;
        }
       checar_ganador();
       C8.setEnabled(false);
    }//GEN-LAST:event_C8ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        //Posicion3.7
        
       if(cont==0){
            C3.setText("X");
            cont++;
            pos[21]=1;
            jugador1[ind1++]=21;
        }
         else{
            C3.setText("O");
            cont--;
            pos[21]=2;
            jugador2[ind2++]=21;
        }
       checar_ganador();
       C3.setEnabled(false);
    }//GEN-LAST:event_C3ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        //Posicion3.8
        
       if(cont==0){
            C6.setText("X");
            cont++;
            pos[24]=1;
            jugador1[ind1++]=24;
        }
         else{
            C6.setText("O");
            cont--;
            pos[24]=2;
            jugador2[ind2++]=24;
        }
       checar_ganador();
       C6.setEnabled(false);
    }//GEN-LAST:event_C6ActionPerformed

    private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
        //Posicion3.9
        
       if(cont==0){
            C9.setText("X");
            cont++;
            pos[27]=1;
            jugador1[ind1++]=27;
        }
         else{
            C9.setText("O");
            cont--;
            pos[27]=2;
            jugador2[ind2++]=27;
        }
       checar_ganador();
       C9.setEnabled(false);
    }//GEN-LAST:event_C9ActionPerformed
    
    

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
