/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato3d;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileWriter;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author oriente
 */
public class Gatito extends javax.swing.JFrame {
    int cont=0;
    int pos[]=new int[30];
    int jugadas_ganadoras[]=new int[30];
    int total_jugadas[]=new int[30];
    int jugador1[]=new int[30];
    int jugador2[]=new int[30];
    int ind1=0;
    int ind2=0;
    int contJovas=0;
    File archivo=new File("JugadasGanadas.txt");
    String saludo=" "; //le puse saludo porque fue el de prueba xD 
    int mat[][]=new int[205][205];
    int t=0,maquina=0;
    int vec[]=new int[100];
    int dec2=0;
    int uni2=0;
    int numtemp;
    /**
     * Creates new form Gatito
     */
    public Gatito() {
        initComponents();
        for(int i=0;i<30;i++)
            pos[i]=0;
        LeeFichero();
        
    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gatito().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        J1 = new javax.swing.JButton();
        J4 = new javax.swing.JButton();
        J9 = new javax.swing.JButton();
        J2 = new javax.swing.JButton();
        J5 = new javax.swing.JButton();
        J7 = new javax.swing.JButton();
        J6 = new javax.swing.JButton();
        J8 = new javax.swing.JButton();
        J3 = new javax.swing.JButton();
        J10 = new javax.swing.JButton();
        J13 = new javax.swing.JButton();
        J16 = new javax.swing.JButton();
        J14 = new javax.swing.JButton();
        J17 = new javax.swing.JButton();
        J12 = new javax.swing.JButton();
        J15 = new javax.swing.JButton();
        J18 = new javax.swing.JButton();
        J11 = new javax.swing.JButton();
        J20 = new javax.swing.JButton();
        J25 = new javax.swing.JButton();
        J19 = new javax.swing.JButton();
        J26 = new javax.swing.JButton();
        J23 = new javax.swing.JButton();
        J22 = new javax.swing.JButton();
        J24 = new javax.swing.JButton();
        J21 = new javax.swing.JButton();
        J27 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1ActionPerformed(evt);
            }
        });
        getContentPane().add(J1);
        J1.setBounds(2, 12, 41, 34);

        J4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J4ActionPerformed(evt);
            }
        });
        getContentPane().add(J4);
        J4.setBounds(2, 52, 41, 34);

        J9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J9ActionPerformed(evt);
            }
        });
        getContentPane().add(J9);
        J9.setBounds(104, 92, 41, 34);

        J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J2ActionPerformed(evt);
            }
        });
        getContentPane().add(J2);
        J2.setBounds(53, 12, 41, 34);

        J5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J5ActionPerformed(evt);
            }
        });
        getContentPane().add(J5);
        J5.setBounds(53, 52, 41, 34);

        J7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J7ActionPerformed(evt);
            }
        });
        getContentPane().add(J7);
        J7.setBounds(2, 92, 41, 34);

        J6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J6ActionPerformed(evt);
            }
        });
        getContentPane().add(J6);
        J6.setBounds(104, 52, 41, 34);

        J8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J8ActionPerformed(evt);
            }
        });
        getContentPane().add(J8);
        J8.setBounds(53, 92, 41, 34);

        J3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J3ActionPerformed(evt);
            }
        });
        getContentPane().add(J3);
        J3.setBounds(104, 12, 41, 34);

        J10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J10ActionPerformed(evt);
            }
        });
        getContentPane().add(J10);
        J10.setBounds(189, 141, 41, 34);

        J13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J13ActionPerformed(evt);
            }
        });
        getContentPane().add(J13);
        J13.setBounds(189, 182, 41, 34);

        J16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J16ActionPerformed(evt);
            }
        });
        getContentPane().add(J16);
        J16.setBounds(189, 222, 41, 31);

        J14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J14ActionPerformed(evt);
            }
        });
        getContentPane().add(J14);
        J14.setBounds(236, 182, 40, 34);

        J17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J17ActionPerformed(evt);
            }
        });
        getContentPane().add(J17);
        J17.setBounds(236, 222, 40, 31);

        J12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J12ActionPerformed(evt);
            }
        });
        getContentPane().add(J12);
        J12.setBounds(282, 141, 41, 34);

        J15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J15ActionPerformed(evt);
            }
        });
        getContentPane().add(J15);
        J15.setBounds(282, 182, 38, 34);

        J18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J18ActionPerformed(evt);
            }
        });
        getContentPane().add(J18);
        J18.setBounds(282, 222, 38, 31);

        J11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J11ActionPerformed(evt);
            }
        });
        getContentPane().add(J11);
        J11.setBounds(236, 141, 40, 35);

        J20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J20ActionPerformed(evt);
            }
        });
        getContentPane().add(J20);
        J20.setBounds(424, 264, 41, 35);

        J25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J25ActionPerformed(evt);
            }
        });
        getContentPane().add(J25);
        J25.setBounds(377, 346, 41, 35);

        J19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J19ActionPerformed(evt);
            }
        });
        getContentPane().add(J19);
        J19.setBounds(377, 264, 41, 35);

        J26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J26ActionPerformed(evt);
            }
        });
        getContentPane().add(J26);
        J26.setBounds(423, 346, 43, 35);

        J23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J23ActionPerformed(evt);
            }
        });
        getContentPane().add(J23);
        J23.setBounds(424, 305, 41, 35);

        J22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J22ActionPerformed(evt);
            }
        });
        getContentPane().add(J22);
        J22.setBounds(377, 305, 41, 35);

        J24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J24ActionPerformed(evt);
            }
        });
        getContentPane().add(J24);
        J24.setBounds(472, 305, 41, 35);

        J21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J21ActionPerformed(evt);
            }
        });
        getContentPane().add(J21);
        J21.setBounds(472, 264, 41, 35);

        J27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J27ActionPerformed(evt);
            }
        });
        getContentPane().add(J27);
        J27.setBounds(472, 346, 41, 35);

        jButton1.setText("Turno Computadora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 310, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Compu_vs_humano(){
        //vec[0]=1; vec[1]=4; vec[2]=7; vec[3]=6; vec[4]=3; vec[5]=9;  //vector temporal prueba
        while(vec[t]!=0 && pos[vec[t]]>0)  //Recorre el vector para evitar las casillas que esten ocupadas
            t++;
        if(vec[t]==0) { //Si ya se acabaron las jugadas, juega random
            vec[t]= (int) (Math.random() * 27) + 1;
            System.out.println(" "+vec[t]);
        }
        // Pon la jugada que sigue en el vector de jugadas
            if(vec[t]==1) {  J1.setText("O"); J1.setEnabled(false); }
            if(vec[t]==2) {  J2.setText("O"); J2.setEnabled(false); } 
            if(vec[t]==3) {  J3.setText("O"); J3.setEnabled(false); }
            if(vec[t]==4) {  J4.setText("O"); J4.setEnabled(false); }
            if(vec[t]==5) {  J5.setText("O"); J5.setEnabled(false); }
            if(vec[t]==6) {  J6.setText("O"); J6.setEnabled(false); }
            if(vec[t]==7) {  J7.setText("O"); J7.setEnabled(false); }
            if(vec[t]==8) {  J8.setText("O"); J8.setEnabled(false); }
            if(vec[t]==9) {  J9.setText("O"); J9.setEnabled(false); }
            if(vec[t]==10) {  J10.setText("O"); J10.setEnabled(false); }
            if(vec[t]==11) {  J11.setText("O"); J11.setEnabled(false); }
            if(vec[t]==12) {  J12.setText("O"); J12.setEnabled(false); }
            if(vec[t]==13) {  J13.setText("O"); J13.setEnabled(false); }
            if(vec[t]==15) {  J15.setText("O"); J15.setEnabled(false); }
            if(vec[t]==16) {  J16.setText("O"); J16.setEnabled(false); }
            if(vec[t]==17) {  J17.setText("O"); J17.setEnabled(false); }
            if(vec[t]==18) {  J18.setText("O"); J18.setEnabled(false); }
            if(vec[t]==19) {  J19.setText("O"); J19.setEnabled(false); }
            if(vec[t]==20) {  J20.setText("O"); J20.setEnabled(false); }
            if(vec[t]==21) {  J21.setText("O"); J21.setEnabled(false); }
            if(vec[t]==22) {  J22.setText("O"); J22.setEnabled(false); }
            if(vec[t]==23) {  J23.setText("O"); J23.setEnabled(false); }
            if(vec[t]==24) {  J24.setText("O"); J24.setEnabled(false); }
            if(vec[t]==25) {  J25.setText("O"); J25.setEnabled(false); }
            if(vec[t]==26) {  J26.setText("O"); J26.setEnabled(false); }
            if(vec[t]==27) {  J27.setText("O"); J27.setEnabled(false); }
            cont--;
            pos[vec[t]]=2;
            jugador2[ind2++]=vec[t];
            checar_ganador();
            t++;
        
    }
 //funcion, esta funcion se manda a llamar en guardar ganador 
    private void GuardarTxt(){
        try{
            //vemos la jugada que gano
            try ( //Crear objeto FileWriter que sera el que nos ayude a escribir sobre archivo
                    FileWriter escribir = new FileWriter(archivo,true)) {
                //vemos la jugada que gano
                for(int i=0;i<27;i++){
                    saludo= Integer.toString(jugadas_ganadoras[i]); //lo convierto de entero a string
                    escribir.write(saludo);
                    escribir.write(" ");
                }   //Escribimos en el archivo con el metodo write
                escribir.write("\n");
                //Cerramos la conexion
            }
        }
        //Si existe un problema al escribir cae aqui
        catch(Exception e){
            System.out.println("Error al escribir");
        }
        LeeFichero();
    }
    
    
     
    private void LeeFichero() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        int numero=0;
        try {
            String linea;
             // Apertura del fichero y creacion de BufferedReader para poder
            // hacer una lectura comoda (disponer del metodo readLine()).
            archivo = new File ("JugadasGanadas.txt");
            fr = new FileReader (archivo);
             br = new BufferedReader(fr);
         System.out.println("Leyendo desde archivo");
         // Lectura del fichero
         
         int i=0,k=0,dec=0,uni=0,j=1;
         while((linea=br.readLine())!=null)
                contJovas++;
            numero = (int) (Math.random() * contJovas) + 1;
            numtemp=numero;
            System.out.print("holi");
            
            archivo = new File ("JugadasGanadas.txt");
            fr = new FileReader (archivo);
            br = new BufferedReader(fr);
            
         while((linea=br.readLine())!=null) {     // imprime lo que haya en el archivo
            //System.out.println(linea);
            //contJovas++;
            System.out.print("holoooo");
            if(j<contJovas){
                j++;
            }
            else{
            while(i<linea.length()) {
                if(linea.charAt(i)!=' ' && i+1<linea.length() && linea.charAt(i+1)==' '){
                    vec[k++]=Character.getNumericValue(linea.charAt(i));
                    i++;
                }
                else if(linea.charAt(i)!=' ' && i+1<linea.length() && linea.charAt(i+1)!=' '){
                    dec=Character.getNumericValue(linea.charAt(i));
                    uni=Character.getNumericValue(linea.charAt(i+1));
                    vec[k++]=(dec*10)+uni;
                    i+=2;
                }
                else i++;
                }
                j=contJovas+1;
            }
         } 
      }
      catch(Exception e){
         e.printStackTrace();
      }finally{
         // En el finally cerramos el fichero, para asegurarnos
         // que se cierra tanto si todo va bien como si salta 
         // una excepcion.
         try{                    
            if( null != fr ){   
               fr.close();     
            }                  
         }catch (Exception e2){ 
            e2.printStackTrace();
         }
      }
        System.out.println("\nEl numero aleatorio fue: "+numtemp+" y cont jovas es: "+contJovas+"\n");
      //for(int i=0;i<30;i++)
      //    System.out.print(" "+vec[i]);
      //EligeJugada();
}
    /*public void EligeJugada(){
        int j=1;
        int k=0;
        int l=0;
        int numero;
        File archivo2 = null;
        FileReader fr2 = null;
        BufferedReader br2 = null;
        
        try {
            archivo2 = new File ("JugadasGanadas.txt");
            fr2 = new FileReader (archivo2);
             br2 = new BufferedReader(fr2);
             String linea2;
             while((linea2=br2.readLine())!=null)
                contJovas++;
            numero = (int) (Math.random() * contJovas) + 1;
            numtemp=numero;
            while((linea2=br2.readLine())!=null){
                if(j<numero){
                    j++;
                }
                else{
                    while(k<linea2.length()){
                        if(linea2.charAt(k)!=' ' && k+1<linea2.length() && linea2.charAt(k+1)==' '){
                    vec[l++]=Character.getNumericValue(linea2.charAt(k));
                    k++;
                }
                else if(linea2.charAt(k)!=' ' && k+1<linea2.length() && linea2.charAt(k+1)!=' '){
                    dec2=Character.getNumericValue(linea2.charAt(k));
                    uni2=Character.getNumericValue(linea2.charAt(k+1));
                    vec[l++]=(dec2*10)+uni2;
                    k+=2;
                }
                else k++;   
                 }
                    
                }
            }
            
        } 
              catch(Exception e){
         e.printStackTrace();
      }finally{
         // En el finally cerramos el fichero, para asegurarnos
         // que se cierra tanto si todo va bien como si salta 
         // una excepcion.
         try{                    
            if( null != fr2 ){   
               fr2.close();     
            }                  
         }catch (Exception e2){ 
            e2.printStackTrace();
         }
      }
        System.out.println("\nEl numero aleatorio fue: "+numtemp+" y cont jovas es: "+contJovas+"\n");
        for(int i=0;i<30;i++)
          System.out.print(" "+vec[i]);
    }*/
    
    public void deshabilita(){
        J1.setEnabled(false);
        J2.setEnabled(false);
        J3.setEnabled(false);
        J4.setEnabled(false);
        J5.setEnabled(false);
        J6.setEnabled(false);
        J7.setEnabled(false);
        J8.setEnabled(false);
        J9.setEnabled(false);
        J10.setEnabled(false);
        J11.setEnabled(false);
        J12.setEnabled(false);
        J13.setEnabled(false);
        J15.setEnabled(false);
        J16.setEnabled(false);
        J17.setEnabled(false);
        J18.setEnabled(false);
        J19.setEnabled(false);
        J20.setEnabled(false);
        J21.setEnabled(false);
        J22.setEnabled(false);
        J23.setEnabled(false);
        J24.setEnabled(false);
        J25.setEnabled(false);
        J26.setEnabled(false);
        J27.setEnabled(false);
    }
    
     
    private void guardar_ganador(){
        int tam=0;
        int c=0;
        for(int i=0;i<15;i++) {
                jugadas_ganadoras[c++]=jugador1[i];
                jugadas_ganadoras[c++]=jugador2[i];
        }
        GuardarTxt();
    }
    
    
    
    private void checar_ganador(){//todas las validaciones estan dentro del if XD
        int f=0;
        if(pos[3]==pos[15] && pos[15]==pos[27]&& pos[3]!=0||pos[7]==pos[17] && pos[17]==pos[27]&& pos[7]!=0||pos[1]==pos[11] && pos[11]==pos[21]&& pos[1]!=0||pos[1]==pos[13] && pos[13]==pos[25]&& pos[1]!=0||pos[21]==pos[23] && pos[23]==pos[25]&& pos[21]!=0||pos[19]==pos[23] && pos[23]==pos[27] && pos[19]!=0||pos[21]==pos[24] && pos[24]==pos[27] && pos[21]!=0||pos[20]==pos[23] && pos[23]==pos[26] && pos[20]!=0||pos[19]==pos[22] && pos[22]==pos[25] && pos[19]!=0||pos[25]==pos[26] && pos[26]==pos[27] && pos[25]!=0||pos[22]==pos[23] && pos[23]==pos[24] && pos[22]!=0||pos[19]==pos[20] && pos[20]==pos[21] && pos[19]!=0||pos[16]==pos[17] && pos[17]==pos[18] && pos[16]!=0||pos[10]==pos[11] && pos[11]==pos[12] && pos[10]!=0||pos[12]==pos[15] && pos[15]==pos[18]&& pos[12]!=0||pos[10]==pos[13] && pos[13]==pos[16]&& pos[10]!=0||pos[3]==pos[5] && pos[5]==pos[7] && pos[3]!=0||pos[1]==pos[5] && pos[5]==pos[9] && pos[1]!=0||pos[7]==pos[8] && pos[8]==pos[9] && pos[7]!=0||pos[4]==pos[5] && pos[5]==pos[6]&& pos[4]!=0||pos[1]==pos[4] && pos[4]==pos[7] && pos[1]!=0||pos[2]==pos[5] && pos[5]==pos[8] && pos[2]!=0||pos[3]==pos[6] && pos[6]==pos[9] && pos[3]!=0||pos[1]==pos[2] && pos[2]==pos[3] && pos[1]!=0){
            f=1;
            if(cont!=0) {
                pos[0]=1;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó X");
            }
            else  {
                pos[0]=2;
                JOptionPane.showMessageDialog(null, "Felicidades! Ganó O");
            }  
        }     
       
        if(f==1){
            guardar_ganador();
            deshabilita();
        }       
    }
    
    private void J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1ActionPerformed
        // Posicion 1
        if(cont==0){
            J1.setText("X");
            cont++;
            pos[1]=1;
            jugador1[ind1++]=1;
            checar_ganador();
            J1.setEnabled(false);
        }
        else{ 
            JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J1.setText("O");
            cont--;
            pos[1]=2;
            jugador2[ind2++]=1;*/
        } 
    }//GEN-LAST:event_J1ActionPerformed

    private void J4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J4ActionPerformed
        //Posicion2
        if(cont==0){
            J4.setText("X");
            cont++;
            pos[4]=1;
            jugador1[ind1++]=4;
            checar_ganador();
            J4.setEnabled(false);
        }
         else{ 
            JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J4.setText("O");
            cont--;
            pos[4]=2;
            jugador2[ind2++]=4;*/
        } 
    }//GEN-LAST:event_J4ActionPerformed

    private void J9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J9ActionPerformed
        //Posicion3
        if(cont==0){
            J9.setText("X");
            cont++;
            pos[9]=1;
            jugador1[ind1++]=9;
            checar_ganador();
            J9.setEnabled(false);
        }
         else{ 
            JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J9.setText("O");
            cont--;
            pos[9]=2;
            jugador2[ind2++]=9;*/
        } 
    }//GEN-LAST:event_J9ActionPerformed

    private void J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J2ActionPerformed
        // Posicion4
         if(cont==0){
            J2.setText("X");
            cont++;
            pos[2]=1;
            jugador1[ind1++]=2;
            checar_ganador();
            J2.setEnabled(false);
        }
         else{ 
            JOptionPane.showMessageDialog(null, "Es turno de la computadora"); 
            /*J2.setText("O");
            cont--;
            pos[2]=2;
            jugador2[ind2++]=2;*/
        } 
    }//GEN-LAST:event_J2ActionPerformed

    private void J6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J6ActionPerformed

        // Posicion5
         if(cont==0){
            J6.setText("X");
            cont++;
            pos[6]=1;
            jugador1[ind1++]=6;
            checar_ganador();
            J6.setEnabled(false);
        }
         else{
             JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J6.setText("O");
            cont--;
            pos[6]=2;
            jugador2[ind2++]=6; */
        }
    }//GEN-LAST:event_J6ActionPerformed

    private void J8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J8ActionPerformed
           // Posicion6
         if(cont==0){
            J8.setText("X");
            cont++;
            pos[8]=1;
            jugador1[ind1++]=8;
            checar_ganador();
            J8.setEnabled(false);
        }
         else{
             JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J8.setText("O");
            cont--;
            pos[8]=2;
            jugador2[ind2++]=8;*/
        }
    }//GEN-LAST:event_J8ActionPerformed

    private void J3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J3ActionPerformed
        // Posicion7
         if(cont==0){
            J3.setText("X");
            cont++;
            pos[3]=1;
            jugador1[ind1++]=3;
            checar_ganador();
            J3.setEnabled(false);
        }
         else{
             JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J3.setText("O");
            cont--;
            pos[3]=2;
            jugador2[ind2++]=3;*/
        }
    }//GEN-LAST:event_J3ActionPerformed

    private void J5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J5ActionPerformed
         // Posicion8
         
         if(cont==0){
            J5.setText("X");
            cont++;
            pos[5]=1;
            jugador1[ind1++]=5;
            checar_ganador();
            J5.setEnabled(false);
        }
         else{
             JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J5.setText("O");
            cont--;
            pos[5]=2;
            jugador2[ind2++]=5;*/
        }
    }//GEN-LAST:event_J5ActionPerformed

    private void J7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J7ActionPerformed
       
        // Posicion9
         if(cont==0){
            J7.setText("X");
            cont++;
            pos[7]=1;
            jugador1[ind1++]=7;
            checar_ganador();
            J7.setEnabled(false);
        }
         else{
             JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J7.setText("O");
            cont--;
            pos[7]=2;
            jugador2[ind2++]=7;*/
        }
    }//GEN-LAST:event_J7ActionPerformed

    private void J10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J10ActionPerformed
        //Posicion2.1
        
       if(cont==0){
            J10.setText("X");
            cont++;
            pos[10]=1;
            jugador1[ind1++]=10;
            checar_ganador();
            J10.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J10.setText("O");
            cont--;
            pos[10]=2;
            jugador2[ind2++]=10;*/
        }
    }//GEN-LAST:event_J10ActionPerformed

    private void J13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J13ActionPerformed
         //Posicion2.2
       
       if(cont==0){
            J13.setText("X");
            cont++;
            pos[13]=1;
            jugador1[ind1++]=13;
            checar_ganador();
            J13.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
          /*  J13.setText("O");
            cont--;
            pos[13]=2;
            jugador2[ind2++]=13;*/
        }
    }//GEN-LAST:event_J13ActionPerformed

    private void J16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J16ActionPerformed
           //Posicion2.3
         
       if(cont==0){
            J16.setText("X");
            cont++;
            pos[16]=1;
            jugador1[ind1++]=16;
            checar_ganador();
            J16.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J16.setText("O");
            cont--;
            pos[16]=2;
            jugador2[ind2++]=16;*/
        }
    }//GEN-LAST:event_J16ActionPerformed

    private void J11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J11ActionPerformed
             //Posicion2.4
          
       if(cont==0){
            J11.setText("X");
            cont++;
            pos[11]=1;
            jugador1[ind1++]=11;
            checar_ganador();
            J11.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J11.setText("O");
            cont--;
            pos[11]=2;
            jugador2[ind2++]=11;*/
        }
    }//GEN-LAST:event_J11ActionPerformed

    private void J14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J14ActionPerformed
              //Posicion2.5
              J14.setBackground(java.awt.Color.red);
       /*if(cont==0){
            jButton14.setText("X");
            cont++;
        }
         else{
            jButton14.setText("O");
            cont--;
        }*/
    }//GEN-LAST:event_J14ActionPerformed

    private void J17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J17ActionPerformed
              //Posicion2.6
              
       if(cont==0){
            J17.setText("X");
            cont++;
            pos[17]=1;
            jugador1[ind1++]=17;
            checar_ganador();
            J17.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J17.setText("O");
            cont--;
            pos[17]=2;
            jugador2[ind2++]=17;*/
        }
    }//GEN-LAST:event_J17ActionPerformed

    private void J12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J12ActionPerformed
               //Posicion2.7
              
       if(cont==0){
            J12.setText("X");
            cont++;
            pos[12]=1;
            jugador1[ind1++]=12;
            checar_ganador();
            J12.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J12.setText("O");
            cont--;
            pos[12]=2;
            jugador2[ind2++]=12;*/
        }
    }//GEN-LAST:event_J12ActionPerformed

    private void J15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J15ActionPerformed
                //Posicion2.8
                
       if(cont==0){
            J15.setText("X");
            cont++;
            pos[15]=1;
            jugador1[ind1++]=15;
            checar_ganador();
            J15.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J15.setText("O");
            cont--;
            pos[15]=2;
            jugador2[ind2++]=15;*/
        }
    }//GEN-LAST:event_J15ActionPerformed

    private void J18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J18ActionPerformed
              //Posicion2.9
              
       if(cont==0){
            J18.setText("X");
            cont++;
            pos[18]=1;
            jugador1[ind1++]=18;
            checar_ganador();
            J18.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J18.setText("O");
            cont--;
            pos[18]=2;
            jugador2[ind2++]=18;*/
        }
    }//GEN-LAST:event_J18ActionPerformed

    private void J19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J19ActionPerformed
               //Posicion3.1
               
       if(cont==0){
            J19.setText("X");
            cont++;
            pos[19]=1;
            jugador1[ind1++]=19;
            checar_ganador();
            J19.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J19.setText("O");
            cont--;
            pos[19]=2;
            jugador2[ind2++]=19;*/
        }
    }//GEN-LAST:event_J19ActionPerformed

    private void J22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J22ActionPerformed
                 //Posicion3.2
                 
       if(cont==0){
            J22.setText("X");
            cont++;
            pos[22]=1;
            jugador1[ind1++]=22;
            checar_ganador();
            J22.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J22.setText("O");
            cont--;
            pos[22]=2;
            jugador2[ind2++]=22;*/
        }
    }//GEN-LAST:event_J22ActionPerformed

    private void J25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J25ActionPerformed
                    //Posicion3.3
                   
       if(cont==0){
            J25.setText("X");
            cont++;
            pos[25]=1;
            jugador1[ind1++]=25;
            checar_ganador();
            J25.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J25.setText("O");
            cont--;
            pos[25]=2;
            jugador2[ind2++]=25;*/
        }
    }//GEN-LAST:event_J25ActionPerformed

    private void J20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J20ActionPerformed
        //Posicion3.4
        
       if(cont==0){
            J20.setText("X");
            cont++;
            pos[20]=1;
            jugador1[ind1++]=20;
            checar_ganador();
            J20.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J20.setText("O");
            cont--;
            pos[20]=2;
            jugador2[ind2++]=20;*/
        }
    }//GEN-LAST:event_J20ActionPerformed

    private void J23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J23ActionPerformed
        //Posicion3.5
        
       if(cont==0){
            J23.setText("X");
            cont++;
            pos[23]=1;
            jugador1[ind1++]=23;
            checar_ganador();
            J23.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J23.setText("O");
            cont--;
            pos[23]=2;
            jugador2[ind2++]=23;*/
        }
    }//GEN-LAST:event_J23ActionPerformed

    private void J26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J26ActionPerformed
        // TODO add your handling code here:
        //Posicion3.6
        
       if(cont==0){
            J26.setText("X");
            cont++;
            pos[26]=1;
            jugador1[ind1++]=26;
            checar_ganador();
            J26.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
            /*J26.setText("O");
            cont--;
            pos[26]=2;
            jugador2[ind2++]=26;*/
        }
    }//GEN-LAST:event_J26ActionPerformed

    private void J21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J21ActionPerformed
        //Posicion3.7
        
       if(cont==0){
            J21.setText("X");
            cont++;
            pos[21]=1;
            jugador1[ind1++]=21;
            checar_ganador();
            J21.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
         /*   J21.setText("O");
            cont--;
            pos[21]=2;
            jugador2[ind2++]=21;*/
        }
    }//GEN-LAST:event_J21ActionPerformed

    private void J24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J24ActionPerformed
        //Posicion3.8
        
       if(cont==0){
            J24.setText("X");
            cont++;
            pos[24]=1;
            jugador1[ind1++]=24;
            checar_ganador();
            J24.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
           /* J24.setText("O");
            cont--;
            pos[24]=2;
            jugador2[ind2++]=24;*/
        }
    }//GEN-LAST:event_J24ActionPerformed

    private void J27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J27ActionPerformed
        //Posicion3.9
        
       if(cont==0){
            J27.setText("X");
            cont++;
            pos[27]=1;
            jugador1[ind1++]=27;   
            checar_ganador();
            J27.setEnabled(false);
        }
         else{
           JOptionPane.showMessageDialog(null, "Es turno de la computadora");
          /*  J27.setText("O");
            cont--;
            pos[27]=2;
            jugador2[ind2++]=27;*/
        }
    }//GEN-LAST:event_J27ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        maquina=1;
        Compu_vs_humano();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J1;
    private javax.swing.JButton J10;
    private javax.swing.JButton J11;
    private javax.swing.JButton J12;
    private javax.swing.JButton J13;
    private javax.swing.JButton J14;
    private javax.swing.JButton J15;
    private javax.swing.JButton J16;
    private javax.swing.JButton J17;
    private javax.swing.JButton J18;
    private javax.swing.JButton J19;
    private javax.swing.JButton J2;
    private javax.swing.JButton J20;
    private javax.swing.JButton J21;
    private javax.swing.JButton J22;
    private javax.swing.JButton J23;
    private javax.swing.JButton J24;
    private javax.swing.JButton J25;
    private javax.swing.JButton J26;
    private javax.swing.JButton J27;
    private javax.swing.JButton J3;
    private javax.swing.JButton J4;
    private javax.swing.JButton J5;
    private javax.swing.JButton J6;
    private javax.swing.JButton J7;
    private javax.swing.JButton J8;
    private javax.swing.JButton J9;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
